/**
 * The global Next.js types, without the build-artifact imports.
 *
 * `next-env.d.ts` is regenerated by Next on every `next dev` / `next build`, is
 * gitignored, and since Next 16 its body is:
 *
 *     /// <reference types="next" />
 *     /// <reference types="next/image-types/global" />
 *     import "./.next/dev/types/routes.d.ts";
 *     import "./.next/dev/types/root-params.d.ts";
 *
 * Those two imports are the problem `tsconfig.typecheck.json` exists to avoid.
 * An `exclude` only filters what the `include` globs pull in; it cannot drop a
 * file another included file imports. So excluding `.next/**` stopped meaning
 * anything the moment `next-env.d.ts` started importing into it, and the
 * source-health typecheck went back to reading gitignored build output — which
 * is exactly the failure `docs/outstanding-issues.md` `#210` describes.
 *
 * It is not hypothetical. On 2026-09-01 `next dev` left
 * `.next/dev/types/routes.d.ts` with a stray fragment (`d": {}`) where a shorter
 * write had not truncated a longer previous file, and `npm run typecheck`
 * reported 106 syntax errors against source that was completely sound. Deleting
 * `.next` made it pass instantly.
 *
 * This file carries the half of `next-env.d.ts` that is real type information —
 * the two reference directives, which resolve inside `node_modules` — and none
 * of the half that points at build output. `tsconfig.typecheck.json` includes
 * this and excludes `next-env.d.ts`; `tsconfig.json` still uses the real one, so
 * `next build` continues to typecheck route signatures against actual routes.
 *
 * Keep it in step with `next-env.d.ts`'s reference directives on a Next upgrade.
 * `tests/typecheck-config-isolation.test.ts` fails if a new directive appears
 * there and not here, and if either the include or the exclude is undone.
 */

/// <reference types="next" />
/// <reference types="next/image-types/global" />
