/**
 * Synthetic ward-team contacts for the prototype directory and the wards index.
 * Extensions and nurse-manager names are fixture data. They are not live WA Health lines.
 */
export interface WardMetadata {
  num: string;
  ext: string;
  vocera: string;
  criteria: string;
  mhaForms: string;
  security: string;
  securityTone: "danger" | "warn" | "good" | "accent" | "gilt";
}

export const WARD_METADATA: Record<string, WardMetadata> = {
  // 22 Authentic Inpatient Units in allUnits()
  "rph-adult-secure": {
    num: "Brian O'Connor",
    ext: "2105",
    vocera: "#NUM-21",
    criteria: "Inner-city high-acuity crisis assessment, severe behavioral disturbance, and complex dual diagnosis.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  "rph-older-adult": {
    num: "Andrew Scott",
    ext: "3825",
    vocera: "#NUM-39",
    criteria:
      "Specialised psychogeriatric inpatient unit for acute organic and functional psychiatric disorders in older adults.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "scgh-adult-open": {
    num: "David Stirling",
    ext: "3490",
    vocera: "#NUM-34",
    criteria: "General acute psychiatric admissions for NMHS catchment with co-morbid acute medical complexity.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "scgh-older-adult": {
    num: "Helen Zhang",
    ext: "2930",
    vocera: "#NUM-29",
    criteria: "Sub-acute geriatric mental health rehabilitation and severe BPSD management for older adults.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "fsh-adult-secure": {
    num: "Jason Miller",
    ext: "5182",
    vocera: "#NUM-51",
    criteria: "High-dependency acute assessment and psychiatric intensive care for southern metropolitan corridor.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  "fsh-older-adult": {
    num: "Simon Ross",
    ext: "4118",
    vocera: "#NUM-42",
    criteria: "Specialised psychogeriatric assessment and dementia-related behavioral support for Rockingham-Kwinana.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "arm-adult-open": {
    num: "Patricia Wright",
    ext: "3820",
    vocera: "#NUM-38",
    criteria: "Acute inpatient psychiatric care for south-east metropolitan catchment under WA Mental Health Act.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "sjgm-adult-open": {
    num: "Emma Wilson",
    ext: "7308",
    vocera: "#NUM-73",
    criteria: "Eastern corridor acute adult admissions, emergency department liaison transfers, and crisis beds.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "rgh-adult-secure": {
    num: "Jessica Howard",
    ext: "6100",
    vocera: "#NUM-61",
    criteria: "South-west metropolitan acute mental health admissions and emergency liaison transfers.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  "fre-adult-open": {
    num: "Fiona Campbell",
    ext: "4112",
    vocera: "#NUM-41",
    criteria: "South-west coastal corridor acute psychiatric intake, multidisciplinary stabilization, and crisis care.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "fre-older-adult": {
    num: "Graeme Bell",
    ext: "6140",
    vocera: "#NUM-62",
    criteria: "Older adult acute psychogeriatric intake and behavioral management for Fremantle catchment.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "bty-adult-secure": {
    num: "Liam Foster",
    ext: "3150",
    vocera: "#NUM-35",
    criteria: "Secure high-dependency containment, crisis stabilization, and psychiatric intensive nursing.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  "bty-older-adult": {
    num: "Gary Davies",
    ext: "7314",
    vocera: "#NUM-74",
    criteria:
      "Older adult assessment, diagnostic workup, and community transition planning for Eastern Hills catchment.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "bty-youth": {
    num: "Timothy Lee",
    ext: "1902",
    vocera: "#NUM-19",
    criteria: "Specialised youth early psychosis intervention and recovery program for young adults aged 16–24.",
    mhaForms: "Form 1A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "gry-adult-secure": {
    num: "Clare Douglas",
    ext: "4102",
    vocera: "#NUM-41",
    criteria:
      "Adults 18–64 under Form 1A/Form 6A requiring intensive psychiatric containment and high-dependency nursing.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  "gry-older-adult": {
    num: "Marcus Vance",
    ext: "2190",
    vocera: "#NUM-21",
    criteria:
      "Older adults 65+ experiencing acute neuropsychiatric decompensation, behavioral BPSD, or late-onset psychosis.",
    mhaForms: "Form 1A, Form 2, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "alb-adult-open": {
    num: "Karen Hughes",
    ext: "2224",
    vocera: "#NUM-22",
    criteria: "Regional adult psychiatric unit for Great Southern region with telemetry link to Perth State Bed Desk.",
    mhaForms: "Form 1A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "bun-adult-open": {
    num: "Stephen Clarke",
    ext: "9014",
    vocera: "#NUM-90",
    criteria: "Regional high-dependency acute psychiatric intake and assessment for South West WA.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "brm-adult-secure": {
    num: "Bradley King",
    ext: "8420",
    vocera: "#NUM-84",
    criteria: "Kimberley regional acute culturally-grounded mental health inpatient unit with RFDS coordination.",
    mhaForms: "Form 4A, Form 6A, CLMA Remand",
    security: "All locked",
    securityTone: "danger",
  },
  "ger-adult-open": {
    num: "Rachel Adams",
    ext: "3140",
    vocera: "#NUM-31",
    criteria: "Midwest regional acute psychiatric intake, stabilization, and crisis admissions.",
    mhaForms: "Form 1A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "sjgs-adult-open": {
    num: "Julian Croft",
    ext: "3310",
    vocera: "#NUM-33",
    criteria:
      "Private adult voluntary inpatient stabilization, mood disorder therapies, and anxiety treatment programs.",
    mhaForms: "Voluntary Admissions, Form 1A",
    security: "All open",
    securityTone: "good",
  },
  "sjgs-adult-secure": {
    num: "Sophie Turner",
    ext: "9901",
    vocera: "#NUM-99",
    criteria: "Private secure high-dependency crisis stabilization and psychiatric care.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
  // Legacy aliases for backward compatibility with mockups
  "armadale-adult": {
    num: "Patricia Wright",
    ext: "3820",
    vocera: "#NUM-38",
    criteria: "Acute inpatient psychiatric care for south-east metropolitan catchment under WA Mental Health Act.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "midland-adult": {
    num: "Emma Wilson",
    ext: "7308",
    vocera: "#NUM-73",
    criteria: "Eastern corridor acute adult admissions, emergency department liaison transfers, and crisis beds.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "fremantle-adult-open": {
    num: "Fiona Campbell",
    ext: "4112",
    vocera: "#NUM-41",
    criteria: "South-west coastal corridor acute psychiatric intake, multidisciplinary stabilization, and crisis care.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All open",
    securityTone: "good",
  },
  "graylands-dorrington": {
    num: "Clare Douglas",
    ext: "4102",
    vocera: "#NUM-41",
    criteria:
      "Adults 18–64 under Form 1A/Form 6A requiring intensive psychiatric containment and high-dependency nursing.",
    mhaForms: "Form 1A, Form 3A, Form 6A",
    security: "All locked",
    securityTone: "danger",
  },
};
