// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Written by `scripts/ward-flow/build-reference-registry.mjs` from the prepared WA reference pack
// at `docs/ward-flow/reference-data/entities.json` (pack generated 2026-09-17T16:54:00+08:00).
// Regenerate with `npm run ward:reference:build`; `npm run check:ward-reference` fails if this
// file and the pack have drifted apart.
//
// 🔴 THIS FILE CARRIES NO NUMBERS, AND THAT IS THE DESIGN. Every row in the pack is marked
// `operational_use_approved: false` and `automatic_routing_approved: false`. Bed counts, capacity
// assertions and catchments are deliberately NOT generated into `src/`, so no unratified figure can
// reach a screen by being imported from here. `tests/ward-reference-registry.test.ts` asserts the
// absence structurally rather than trusting this comment.
//
// These are real names of real Western Australian services. They are NOT an assertion that any
// service has approved this record, that a ward is currently open, or that a published bed figure
// is current. Ward Flow's own bed numbers remain invented; see the header of `ward-sites.ts`.

export type ReferenceEntityKind =
  "facility" | "emergency_department" | "named_ward" | "named_unit" | "community_service";

export type ReferenceEntity = {
  /** The pack's stable research id. NOT a provider's operational identifier. */
  readonly id: string;
  readonly name: string;
  readonly kind: ReferenceEntityKind;
  /** Null for a community service, which belongs to a health service rather than a building. */
  readonly facilityId: string | null;
  /** The pack's own cohort wording, which is wider than Ward Flow's three-value `Cohort` union
   *  and must never be copied into it. */
  readonly cohort: string | null;
  readonly hsp: string | null;
  readonly sourceIds: readonly string[];
};

export const WARD_REFERENCE_ENTITIES: readonly ReferenceEntity[] = [
  {
    id: "c-arm",
    name: "Armadale CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-clarkson",
    name: "Clarkson CAMHS — Ainsbury Parade",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-fre",
    name: "Fremantle CAMHS — Murdoch Community Hub",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH", "C-FRE"],
  },
  {
    id: "c-hillarys",
    name: "Hillarys CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-peel",
    name: "Peel CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-rk",
    name: "Rockingham CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-shenton",
    name: "Shenton CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-swan",
    name: "Swan CAMHS — Midland Community Hub",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "c-warwick",
    name: "Warwick CAMHS",
    kind: "community_service",
    facilityId: null,
    cohort: "Children and adolescents, up to 18",
    hsp: "CAHS",
    sourceIds: ["C-CLIN", "C-CATCH"],
  },
  {
    id: "e-arm-old",
    name: "Armadale Older Adult Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "EMHS",
    sourceIds: ["E-ARM-OLD", "E-CENSUS"],
  },
  {
    id: "e-armadale",
    name: "Armadale community mental health / Orchard Avenue Centre",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "EMHS",
    sourceIds: ["E-ARM", "E-CENSUS"],
  },
  {
    id: "e-bentley",
    name: "Bentley Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "EMHS",
    sourceIds: ["E-BHS", "E-CENSUS", "E-CATCH"],
  },
  {
    id: "e-bentley-old",
    name: "Bentley older adult community service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "EMHS",
    sourceIds: ["E-CENSUS", "E-BHS"],
  },
  {
    id: "e-city",
    name: "City East Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "EMHS",
    sourceIds: ["E-CITY", "E-CENSUS", "E-CATCH"],
  },
  {
    id: "e-city-old",
    name: "City East older adult community service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "EMHS",
    sourceIds: ["E-CENSUS", "E-CITY", "E-RPH"],
  },
  {
    id: "e-midland",
    name: "Midland Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "EMHS",
    sourceIds: ["E-CENSUS", "E-MID-C", "E-CATCH", "E-MID-OFFICIAL"],
  },
  {
    id: "e-midland-old",
    name: "Midland older adult community service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "EMHS",
    sourceIds: ["E-CENSUS"],
  },
  {
    id: "n-butler",
    name: "Butler Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–65",
    hsp: "NMHS",
    sourceIds: ["N-CLIN", "N-CATCH"],
  },
  {
    id: "n-lowerwest-old",
    name: "Lower West Older Adult Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "NMHS",
    sourceIds: ["N-OLDER", "N-OA-CATCH"],
  },
  {
    id: "n-mirra",
    name: "Mirrabooka Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–65",
    hsp: "NMHS",
    sourceIds: ["N-CLIN", "N-CATCH"],
  },
  {
    id: "n-osborne",
    name: "Osborne Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–65",
    hsp: "NMHS",
    sourceIds: ["N-CLIN", "N-CATCH"],
  },
  {
    id: "n-osborne-old",
    name: "Osborne Park Older Adult Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "NMHS",
    sourceIds: ["N-OLDER", "N-OA-CATCH"],
  },
  {
    id: "n-subiaco",
    name: "Subiaco Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–65",
    hsp: "NMHS",
    sourceIds: ["N-CLIN", "N-CATCH"],
  },
  {
    id: "n-wanneroo",
    name: "Wanneroo Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–65",
    hsp: "NMHS",
    sourceIds: ["N-CLIN", "N-CATCH"],
  },
  {
    id: "n-wanneroo-old",
    name: "Wanneroo Older Adult Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "NMHS",
    sourceIds: ["N-OLDER", "N-OA-CATCH"],
  },
  {
    id: "s-cock",
    name: "Cockburn Community Treatment Team",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "SMHS",
    sourceIds: ["S-COMM", "S-CATCH"],
  },
  {
    id: "s-fre",
    name: "Fremantle Community Treatment Team",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "SMHS",
    sourceIds: ["S-COMM", "S-CATCH"],
  },
  {
    id: "s-fre-old",
    name: "Fremantle Older Adult Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "SMHS",
    sourceIds: ["S-FRE-OLD"],
  },
  {
    id: "s-melville",
    name: "Melville Community Treatment Team",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "SMHS",
    sourceIds: ["S-COMM", "S-CATCH"],
  },
  {
    id: "s-park-old",
    name: "PaRK Older Adult Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Older adult",
    hsp: "SMHS",
    sourceIds: ["S-PARK"],
  },
  {
    id: "s-peel",
    name: "Peel Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "18–64",
    hsp: "SMHS",
    sourceIds: ["S-PARK", "S-CATCH"],
  },
  {
    id: "s-rk",
    name: "Rockingham Kwinana Community Mental Health Service",
    kind: "community_service",
    facilityId: null,
    cohort: "Adult",
    hsp: "SMHS",
    sourceIds: ["S-PARK", "S-CATCH"],
  },
  {
    id: "ed-ahs",
    name: "Armadale Health Service",
    kind: "emergency_department",
    facilityId: "ahs",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ED-WA", "E-CENSUS"],
  },
  {
    id: "ed-fsh",
    name: "Fiona Stanley Hospital",
    kind: "emergency_department",
    facilityId: "fsh",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-ADULT"],
  },
  {
    id: "ed-hol",
    name: "Hollywood Private Hospital",
    kind: "emergency_department",
    facilityId: "hol",
    cohort: null,
    hsp: null,
    sourceIds: ["ED-HOL"],
  },
  {
    id: "ed-jhc",
    name: "Joondalup Health Campus",
    kind: "emergency_department",
    facilityId: "jhc",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "JHC"],
  },
  {
    id: "ed-kemh",
    name: "King Edward Memorial Hospital",
    kind: "emergency_department",
    facilityId: "kemh",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "KEMH"],
  },
  {
    id: "ed-mid",
    name: "St John of God Midland Public Hospital",
    kind: "emergency_department",
    facilityId: "mid",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ED-WA", "MID-BEDS"],
  },
  {
    id: "ed-mur",
    name: "St John of God Murdoch Hospital",
    kind: "emergency_department",
    facilityId: "mur",
    cohort: null,
    hsp: null,
    sourceIds: ["ED-MUR"],
  },
  {
    id: "ed-pch",
    name: "Perth Children's Hospital",
    kind: "emergency_department",
    facilityId: "pch",
    cohort: null,
    hsp: "CAHS",
    sourceIds: ["ED-WA", "C-INPT"],
  },
  {
    id: "ed-peel",
    name: "Peel Health Campus",
    kind: "emergency_department",
    facilityId: "peel",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-PARK"],
  },
  {
    id: "ed-rgh",
    name: "Rockingham General Hospital",
    kind: "emergency_department",
    facilityId: "rgh",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-PARK"],
  },
  {
    id: "ed-rph",
    name: "Royal Perth Hospital",
    kind: "emergency_department",
    facilityId: "rph",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ED-WA", "E-RPH"],
  },
  {
    id: "ed-scgh",
    name: "Sir Charles Gairdner Hospital",
    kind: "emergency_department",
    facilityId: "scgh",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "N-SCGH"],
  },
  {
    id: "abb",
    name: "Abbotsford Private Hospital",
    kind: "facility",
    facilityId: "abb",
    cohort: null,
    hsp: null,
    sourceIds: ["P-ABB"],
  },
  {
    id: "ahs",
    name: "Armadale Health Service",
    kind: "facility",
    facilityId: "ahs",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["E-ARM", "E-CENSUS"],
  },
  {
    id: "albany",
    name: "Albany Health Campus",
    kind: "facility",
    facilityId: "albany",
    cohort: null,
    hsp: "WACHS",
    sourceIds: ["W-ALB-APU"],
  },
  {
    id: "bhs",
    name: "Bentley Health Service",
    kind: "facility",
    facilityId: "bhs",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["E-BHS", "E-CENSUS"],
  },
  {
    id: "broome",
    name: "Broome Health Campus",
    kind: "facility",
    facilityId: "broome",
    cohort: null,
    hsp: "WACHS",
    sourceIds: ["W-BROOME-IPU"],
  },
  {
    id: "bunbury",
    name: "Bunbury Regional Hospital",
    kind: "facility",
    facilityId: "bunbury",
    cohort: null,
    hsp: "WACHS",
    sourceIds: ["W-BUN-MHOA"],
  },
  {
    id: "cock",
    name: "Cockburn Health",
    kind: "facility",
    facilityId: "cock",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["S-WARDS", "S-COCK-2026"],
  },
  {
    id: "fre",
    name: "Fremantle Hospital",
    kind: "facility",
    facilityId: "fre",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["S-WARDS", "S-FRE-40"],
  },
  {
    id: "fsh",
    name: "Fiona Stanley Hospital",
    kind: "facility",
    facilityId: "fsh",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-FSH-Y", "S-FSH-MBU"],
  },
  {
    id: "geraldton",
    name: "Geraldton Health Campus",
    kind: "facility",
    facilityId: "geraldton",
    cohort: null,
    hsp: "WACHS",
    sourceIds: ["W-GER-AUG", "W-GER-PROJECT"],
  },
  {
    id: "gray",
    name: "Graylands Hospital",
    kind: "facility",
    facilityId: "gray",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["N-GRAY"],
  },
  {
    id: "hol",
    name: "Hollywood Private Hospital",
    kind: "facility",
    facilityId: "hol",
    cohort: null,
    hsp: null,
    sourceIds: ["ED-HOL", "P-HOL", "C-INPT"],
  },
  {
    id: "jhc",
    name: "Joondalup Health Campus",
    kind: "facility",
    facilityId: "jhc",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "JHC"],
  },
  {
    id: "kalgoorlie",
    name: "Kalgoorlie Health Campus",
    kind: "facility",
    facilityId: "kalgoorlie",
    cohort: null,
    hsp: "WACHS",
    sourceIds: ["W-KAL-IPU"],
  },
  {
    id: "kemh",
    name: "King Edward Memorial Hospital",
    kind: "facility",
    facilityId: "kemh",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "KEMH"],
  },
  {
    id: "marian",
    name: "Marian Centre",
    kind: "facility",
    facilityId: "marian",
    cohort: null,
    hsp: null,
    sourceIds: ["P-MARIAN"],
  },
  {
    id: "mid",
    name: "St John of God Midland Public Hospital",
    kind: "facility",
    facilityId: "mid",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ED-WA", "MID-BEDS"],
  },
  {
    id: "mlh",
    name: "Mount Lawley Hospital",
    kind: "facility",
    facilityId: "mlh",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ML-TRANSFER", "ML-HISTORY", "E-CENSUS"],
  },
  {
    id: "mur",
    name: "St John of God Murdoch Hospital",
    kind: "facility",
    facilityId: "mur",
    cohort: null,
    hsp: null,
    sourceIds: ["ED-MUR"],
  },
  {
    id: "oph",
    name: "Osborne Park Hospital",
    kind: "facility",
    facilityId: "oph",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["N-OLDER", "N-MH"],
  },
  {
    id: "pch",
    name: "Perth Children's Hospital",
    kind: "facility",
    facilityId: "pch",
    cohort: null,
    hsp: "CAHS",
    sourceIds: ["ED-WA", "C-INPT"],
  },
  {
    id: "peel",
    name: "Peel Health Campus",
    kind: "facility",
    facilityId: "peel",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-PARK"],
  },
  {
    id: "perthclinic",
    name: "Perth Clinic",
    kind: "facility",
    facilityId: "perthclinic",
    cohort: null,
    hsp: null,
    sourceIds: ["P-PERTH"],
  },
  {
    id: "rgh",
    name: "Rockingham General Hospital",
    kind: "facility",
    facilityId: "rgh",
    cohort: null,
    hsp: "SMHS",
    sourceIds: ["ED-WA", "S-PARK"],
  },
  {
    id: "rph",
    name: "Royal Perth Hospital",
    kind: "facility",
    facilityId: "rph",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["ED-WA", "E-RPH", "E-CENSUS"],
  },
  {
    id: "scgh",
    name: "Sir Charles Gairdner Hospital",
    kind: "facility",
    facilityId: "scgh",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["ED-WA", "N-SCGH"],
  },
  {
    id: "selby",
    name: "Selby older adult inpatient service",
    kind: "facility",
    facilityId: "selby",
    cohort: null,
    hsp: "NMHS",
    sourceIds: ["N-OLDER", "N-MH", "OCP"],
  },
  {
    id: "tcu",
    name: "EMHS Transitional Care Unit",
    kind: "facility",
    facilityId: "tcu",
    cohort: null,
    hsp: "EMHS",
    sourceIds: ["E-CENSUS"],
  },
  {
    id: "albany-apu",
    name: "Great Southern Acute Psychiatric Unit",
    kind: "named_unit",
    facilityId: "albany",
    cohort: "Adult / local criteria not fully reviewed",
    hsp: null,
    sourceIds: ["W-ALB-APU"],
  },
  {
    id: "bhs-emyu",
    name: "East Metropolitan Youth Unit (EMyU)",
    kind: "named_unit",
    facilityId: "bhs",
    cohort: "Youth",
    hsp: null,
    sourceIds: ["E-CENSUS", "OCP"],
  },
  {
    id: "broome-mabu-liyan",
    name: "Mabu Liyan / Broome Mental Health Unit",
    kind: "named_unit",
    facilityId: "broome",
    cohort: "Local eligibility not fully reviewed",
    hsp: null,
    sourceIds: ["W-BROOME-IPU"],
  },
  {
    id: "bunbury-apu",
    name: "Bunbury Acute Psychiatric Unit",
    kind: "named_unit",
    facilityId: "bunbury",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["W-BUN-MHOA"],
  },
  {
    id: "dryandra",
    name: "Dryandra secure rehabilitation unit",
    kind: "named_unit",
    facilityId: "gray",
    cohort: "Forensic",
    hsp: null,
    sourceIds: ["N-FORENSIC"],
  },
  {
    id: "frankland",
    name: "Frankland Centre",
    kind: "named_unit",
    facilityId: "gray",
    cohort: "Forensic",
    hsp: null,
    sourceIds: ["N-FORENSIC"],
  },
  {
    id: "fsh-mbu",
    name: "Mother and Baby Unit",
    kind: "named_unit",
    facilityId: "fsh",
    cohort: "Perinatal",
    hsp: null,
    sourceIds: ["S-FSH-MBU"],
  },
  {
    id: "fsh-youth",
    name: "Mental Health Youth Unit",
    kind: "named_unit",
    facilityId: "fsh",
    cohort: "Youth 16–24",
    hsp: null,
    sourceIds: ["S-FSH-Y"],
  },
  {
    id: "kalgoorlie-mhiu",
    name: "Goldfields Mental Health Inpatient Unit",
    kind: "named_unit",
    facilityId: "kalgoorlie",
    cohort: "Local eligibility not fully reviewed",
    hsp: null,
    sourceIds: ["W-KAL-IPU"],
  },
  {
    id: "kemh-mbu",
    name: "Mother and Baby Unit",
    kind: "named_unit",
    facilityId: "kemh",
    cohort: "Perinatal",
    hsp: null,
    sourceIds: ["KEMH"],
  },
  {
    id: "mlh-uf",
    name: "Ursula Frayne older adult unit",
    kind: "named_unit",
    facilityId: "mlh",
    cohort: "Older adult",
    hsp: null,
    sourceIds: ["OCP", "E-CENSUS", "ML-HISTORY"],
  },
  {
    id: "scgh-mhu",
    name: "Mental Health Unit",
    kind: "named_unit",
    facilityId: "scgh",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["N-SCGH", "N-INPT"],
  },
  {
    id: "ahs-banksia",
    name: "Banksia — older adult inpatient unit",
    kind: "named_ward",
    facilityId: "ahs",
    cohort: "Older adult",
    hsp: null,
    sourceIds: ["E-ARM-OLD", "E-CENSUS"],
  },
  {
    id: "ahs-karri",
    name: "Karri",
    kind: "named_ward",
    facilityId: "ahs",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["E-ARM"],
  },
  {
    id: "ahs-moodjar",
    name: "Moodjar",
    kind: "named_ward",
    facilityId: "ahs",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["E-ARM"],
  },
  {
    id: "ahs-yorgum",
    name: "Yorgum high-dependency unit",
    kind: "named_ward",
    facilityId: "ahs",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["E-ARM"],
  },
  {
    id: "cock-kogolup",
    name: "Kogolup (Ward 1)",
    kind: "named_ward",
    facilityId: "cock",
    cohort: "Adult women",
    hsp: null,
    sourceIds: ["S-WARDS"],
  },
  {
    id: "fre-boodalung",
    name: "Boodalung — open ward",
    kind: "named_ward",
    facilityId: "fre",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["S-BOOD"],
  },
  {
    id: "fre-djiti",
    name: "Djiti djiti (Ward 5.1) — open",
    kind: "named_ward",
    facilityId: "fre",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["S-WARDS"],
  },
  {
    id: "fre-maali",
    name: "Maali (Ward 4.2) — open",
    kind: "named_ward",
    facilityId: "fre",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["S-WARDS"],
  },
  {
    id: "fre-waalitj",
    name: "Waalitj (Ward 4.1) — PICU",
    kind: "named_ward",
    facilityId: "fre",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["S-WARDS"],
  },
  {
    id: "fre-wardong",
    name: "Wardong (Ward 4.3)",
    kind: "named_ward",
    facilityId: "fre",
    cohort: "Older adult",
    hsp: null,
    sourceIds: ["S-WARDS"],
  },
  {
    id: "nickoll",
    name: "Nickoll Ward — CAHS public service",
    kind: "named_ward",
    facilityId: "hol",
    cohort: "Selected adolescents 14–15",
    hsp: null,
    sourceIds: ["C-INPT", "C-SPLIT"],
  },
  {
    id: "pch-5a",
    name: "Ward 5A",
    kind: "named_ward",
    facilityId: "pch",
    cohort: "Child / adolescent",
    hsp: null,
    sourceIds: ["C-INPT", "C-SPLIT"],
  },
  {
    id: "rph-2k",
    name: "Ward 2K",
    kind: "named_ward",
    facilityId: "rph",
    cohort: "Adult",
    hsp: null,
    sourceIds: ["E-RPH"],
  },
  {
    id: "rph-dab",
    name: "Dabakarn",
    kind: "named_ward",
    facilityId: "rph",
    cohort: "Adult complex",
    hsp: null,
    sourceIds: ["E-RPH", "OCP"],
  },
];

const BY_ID = new Map(WARD_REFERENCE_ENTITIES.map((entity) => [entity.id, entity]));

/** The entity with this id, or null. Never a fallback, never the nearest match. */
export function referenceEntity(id: string): ReferenceEntity | null {
  return BY_ID.get(id) ?? null;
}

/** Every entity of one kind, in the generated order. */
export function referenceEntitiesOfKind(kind: ReferenceEntityKind): readonly ReferenceEntity[] {
  return WARD_REFERENCE_ENTITIES.filter((entity) => entity.kind === kind);
}
