#!/usr/bin/env node
/**
 * 🔴 **ONE PAGE SHOWING ALL 38 DRAWINGS AT ONCE — LIVE, NOT AS SCREENSHOTS.**
 *
 *     node scripts/ward-flow/contact-sheet.mjs
 *     then open docs/ward-flow/mockups/CONTACT-SHEET.html in a browser
 *
 * ⚠️ **SCREENSHOTS WERE THE OBVIOUS ANSWER AND THEY ARE THE WRONG ONE, TWICE OVER.** A screenshot
 * goes stale the moment a drawing is edited, silently — the defect this whole estate keeps
 * rediscovering. And these mockups build their own navigation WITH JAVASCRIPT, so a static capture
 * shows a drawing with its navigation missing. **A false finding was reported to the owner from
 * exactly that** on 2026-09-12: a mockup opened as a static snapshot looked like a completely
 * different design, and the difference was reported as a real gap.
 *
 * ✅ **SO EACH TILE IS AN `<iframe>` OF THE REAL FILE.** It runs the drawing's own scripts, it is
 * never out of date, and clicking a tile opens that drawing full size.
 */

import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const DIR = join(process.cwd(), "docs", "ward-flow", "mockups");
const OUT = join(DIR, "CONTACT-SHEET.html");

/** Not current — kept for reference, never built from. Shown last and marked. */
const SUPERSEDED = new Set(["patient-search-console.html", "patient-search-working.html"]);

if (!existsSync(DIR)) {
  console.error(`no mockups directory at ${DIR}`);
  process.exit(2);
}

const all = readdirSync(DIR)
  .filter((f) => f.endsWith(".html") && f !== "CONTACT-SHEET.html")
  .sort();
const current = all.filter((f) => !SUPERSEDED.has(f));
const old = all.filter((f) => SUPERSEDED.has(f));

const title = (f) =>
  f
    .replace(/\.html$/, "")
    .replace(/-third-edition$/, "")
    .replace(/-/g, " ")
    .replace(/^\w/, (c) => c.toUpperCase());

const tile = (f, stale) => `
    <figure class="t${stale ? " stale" : ""}">
      <figcaption><a href="${f}" target="_blank" rel="noopener">${title(f)}</a>${stale ? " <b>superseded</b>" : ""}</figcaption>
      <div class="frame"><iframe src="${f}" loading="lazy" title="${title(f)}" scrolling="no"></iframe></div>
    </figure>`;

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ward Flow — every drawing</title>
<style>
  :root { color-scheme: light dark; --edge: #d3d7dd; --ink: #14161a; --dim: #5b6470; }
  @media (prefers-color-scheme: dark) { :root { --edge: #33383f; --ink: #e8ebef; --dim: #98a1ad; } }
  body { margin: 0; padding: 24px; font: 14px/1.5 system-ui, -apple-system, Segoe UI, sans-serif; color: var(--ink); }
  h1 { font-size: 20px; margin: 0 0 4px; }
  p.lede { margin: 0 0 20px; color: var(--dim); max-width: 70ch; }
  p.lede b { color: var(--ink); }
  p.lede.warn { border-left: 3px solid #c98a2e; padding-left: 12px; }
  h2 { font-size: 15px; margin: 28px 0 12px; padding-top: 14px; border-top: 1px solid var(--edge); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; }
  .t { margin: 0; }
  figcaption { font-size: 13px; margin-bottom: 6px; }
  figcaption a { color: inherit; text-decoration: none; border-bottom: 1px solid var(--edge); }
  figcaption a:hover { border-bottom-color: currentColor; }
  figcaption b { color: #a8391f; font-weight: 600; }
  .frame { position: relative; width: 100%; aspect-ratio: 4 / 3; overflow: hidden;
           border: 1px solid var(--edge); border-radius: 6px; background: #fff; }
  /* The drawings are desktop-width. Render at 1440 and scale the whole tile down. */
  .frame iframe { position: absolute; top: 0; left: 0; width: 1440px; height: 1080px;
                  border: 0; transform-origin: 0 0; transform: scale(0.2083); }
  .stale .frame { opacity: .55; filter: grayscale(.6); }
</style></head>
<body>
<h1>Ward Flow — every drawing, ${current.length} current</h1>
<p class="lede">
  <b>This is the design.</b> Each tile is the real file running its own scripts, not a screenshot —
  so it cannot go out of date, and the navigation each drawing builds with JavaScript is actually
  present. <b>Click any title to open that drawing full size.</b>
  Generated by <code>scripts/ward-flow/contact-sheet.mjs</code>; re-run it after adding a drawing.
</p>
<p class="lede warn">
  &#9888; <b>Open this in a real browser</b> &mdash; double-click the file, or drag it into Chrome,
  Edge or Firefox. <b>Embedded preview panes render local files as static snapshots and show every
  tile blank</b>, because they do not load local iframes or run the drawings' scripts. That is the
  viewer, not the drawings &mdash; and it is the same limitation that produced a false finding about
  these mockups on 2026-09-12.
</p>
<div class="grid">${current.map((f) => tile(f, false)).join("")}
</div>
${old.length ? `<h2>Superseded — kept for reference, never build from these</h2>
<div class="grid">${old.map((f) => tile(f, true)).join("")}
</div>` : ""}
</body></html>
`;

writeFileSync(OUT, html, "utf8");
console.log(`wrote ${OUT} — ${current.length} current, ${old.length} superseded.`);
